// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRjPz1BOedrtPpqRUvx12uLG2XQ_QnbVI',
    appId: '1:660750065239:web:1b0109db00906135508d12',
    messagingSenderId: '660750065239',
    projectId: 'student-job-internship-finder',
    authDomain: 'student-job-internship-finder.firebaseapp.com',
    storageBucket: 'student-job-internship-finder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzce7J6BsxJGoKwrMdSal9I7My89x0ipU',
    appId: '1:660750065239:android:7b9ab649ff4f2dc4508d12',
    messagingSenderId: '660750065239',
    projectId: 'student-job-internship-finder',
    storageBucket: 'student-job-internship-finder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQztD4tJe76m8Pqj0MD67Em6QZqqeDIk',
    appId: '1:660750065239:ios:9594112150c77d77508d12',
    messagingSenderId: '660750065239',
    projectId: 'student-job-internship-finder',
    storageBucket: 'student-job-internship-finder.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBQztD4tJe76m8Pqj0MD67Em6QZqqeDIk',
    appId: '1:660750065239:ios:9594112150c77d77508d12',
    messagingSenderId: '660750065239',
    projectId: 'student-job-internship-finder',
    storageBucket: 'student-job-internship-finder.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRjPz1BOedrtPpqRUvx12uLG2XQ_QnbVI',
    appId: '1:660750065239:web:da918a38abaa671a508d12',
    messagingSenderId: '660750065239',
    projectId: 'student-job-internship-finder',
    authDomain: 'student-job-internship-finder.firebaseapp.com',
    storageBucket: 'student-job-internship-finder.firebasestorage.app',
  );
}
